name: goesPlot
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - cartopy
  - pylint
  - jupyter
  - jupyterlab
  - netcdf4
  - pandas
  - geopandas
  - scipy
  - metpy
  - siphon
  - xarray
  - basemap
  - basemap-data-hires
  - dask
  - pyproj
  - h5py
  - shapely
  - pygrib  # Not available on Windows
  - boto
  #- cfgrib  # Can read GRIB2 on Windows (need version 0.9.7+ for reading HRRR files)
